# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Lily58 nice_nano_v2'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["lily58_left","lily58_right"]'
      nav: '["invertedt"]'
